[package]
name = "gltf-codegen2"
version = "0.1.0"
authors = ["David Harvey-Macaulay <alteous@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = { features = ["full", "default"], version = "0.15" }
