[meta]
kind = "Struct"
ident = "Mesh"
module = "mesh"
docs = "A set of primitives to be rendered."
notes = "A node can contain one mesh.  A node's transform places the mesh in the scene."

[fields.primitives]
ty = "Array"
of = "mesh::Primitive"
json = "primitives"
docs = "An array of primitives, each defining geometry to be rendered with a material."

[fields.weights]
ty = "Array"
of = "Float"
json = "weights"
docs = "An array of weights to be applied to the Morph Targets."

